<a href="https://colab.research.google.com/github/arielbakal/AlgebraLinealComputacional_UBA_FCEN/blob/main/practicas/practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

In [15]:
def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

### Ejercicio 1a

In [20]:
A = np.array ([[1,1,-2,1],[3,-2,1,5],[1,-1,1,2]])
B = np.array([-2,3,2])
print(row_echelon(A))
C = np.linalg.solve(A,B)

[[ 1.   1.  -2.   1. ]
 [ 0.   1.  -1.4 -0.4]
 [ 0.   0.   1.   1. ]]


LinAlgError: ignored

Observamos que el sistema tiene mas de una solucion porque la matriz A no es cuadrada y el sistema compatible, tal cual nos lo dice numpy

### EJERCICIO 1b

In [25]:
A = np.array ([[1,1,1,-2,1,1],[1,-3,1,1,1,0],[3,-5,3,0,3,0]])
print(row_echelon(A))

[[ 1.    1.    1.   -2.    1.    1.  ]
 [ 0.    1.   -0.   -0.75 -0.    0.25]
 [ 0.    0.    0.    0.    0.    1.  ]]


Aca inserte como ultima columna de la matriz, los resultados de las ecuaciones. Se puede observar que hay un absurdo en la ultima fila (0=1) entonces el sistema es incompatible.

### Ejercicio 1c

In [21]:
A = np.array([[1j,(-1-1j),0],[1,-2,1],[1,2j,-1]])
B = np.array([-1,0,2j])
print(row_echelon(A))
C = np.linalg.solve(A,B)

[[ 1. +0.j  -1. +1.j   0. +0.j ]
 [ 0. +0.j   1. -0.j  -0.5+0.5j]
 [ 0. +0.j   0. +0.j   0. +0.j ]]


LinAlgError: ignored

Observamos que el sistema tiene mas de una solucion porque es SCI, pero a diferencia del ejercicio anterior, numpy dice que la matriz es singular. Es decir, que la determinante de A es 0 => A no es inversible => El sistema no tiene unica solucion

### Ejercicio 3

In [27]:
a = 7
b = a + 1
print("b = ", b )

b =  8


In [35]:
# Vectores
v = np.array([1,2,3,-1])
w = np.array([2,3,0,5])
print("v + w = ", v + w ) 
print("2∗v = ", 2*v )
print("v^2 = ", v**2 )

v + w =  [3 5 3 4]
2∗v =  [ 2  4  6 -2]
v^2 =  [1 4 9 1]


In [48]:
# Matrices (ejecutarlos comandos uno a uno para ver los resultados)
A = np.array([[1,2,3,4,5],[0,1,2,3,4],[2,3,4,5,6],[0,0,1,2,3],[0,0,0,0,1]])
print(A)

[[1 2 3 4 5]
 [0 1 2 3 4]
 [2 3 4 5 6]
 [0 0 1 2 3]
 [0 0 0 0 1]]


In [49]:
A[0:2,3:5]

array([[4, 5],
       [3, 4]])

In [50]:
A[ :2,3: ]

array([[4, 5],
       [3, 4]])

In [51]:
A[[0,2,4], : ]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [0, 0, 0, 0, 1]])

In [52]:
ind = np.array([0,2,4])

In [53]:
A[ind,ind]

array([1, 4, 1])

In [54]:
A[ind,ind[:,None]]

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 1]])

In [56]:
# Numeros complejos
(1j)*(1j)

(-1+0j)

In [57]:
(1+2j)*(1j)

(-2+1j)