<a href="https://colab.research.google.com/github/arielbakal/uba_alc/blob/main/laboratorio/clase%205/labo05_DescLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

#### Ejercicio 1 y 2

In [27]:
def elim_gaussiana(A):
    cant_op = 0
    m=A.shape[0]
    n=A.shape[1]
    Ac = A.copy()

    if m!=n:
        print('Matriz no cuadrada')
        return

    for i in range(m-1): # i itera filas

      d = (Ac[i][i]) # Agarro los elementos de la diagonal

      for j in range(m-1-i): # j itera columnas

        s = -(Ac[j+1+i][i]) / d # Obtengo los elementos de cada L_i - I
        cant_op += 2

        for p in range(m-1-i): # p recorre coordanada a coordenada cada fila

          # Modifico cada coord individualmente simulando una fila de L multiplicando a Ac
          Ac[j+1+i][p+1+i] += (s * Ac[i][p+1+i]) 
          cant_op += 2

        # Asigno a un Ac triangulado en el paso i los valores de L_i 
        Ac[j+1+i][i] = -s
        cant_op += 1
            
    # Descompongo A en LU              
    L = np.tril(Ac,-1) + np.eye(A.shape[0]) 
    U = np.triu(Ac)
    
    return L, U, cant_op

In [28]:
def main():
    n = 7
    B = np.eye(n) - np.tril(np.ones((n,n)),-1) 
    B[:n,n-1] = 1
    print('Matriz B \n', B)
    
    L,U,cant_oper = elim_gaussiana(B)
    
    print('Matriz L \n', L)
    print('Matriz U \n', U)
    print('Cantidad de operaciones: ', cant_oper)
    print('B=LU? ' , 'Si!' if np.allclose(np.linalg.norm(B - L@U, 1), 0) else 'No!')
    print('Norma infinito de U: ', np.max(np.sum(np.abs(U), axis=1)) )

In [29]:
main()

Matriz B 
 [[ 1.  0.  0.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  0.  0.  1.]
 [-1. -1.  1.  0.  0.  0.  1.]
 [-1. -1. -1.  1.  0.  0.  1.]
 [-1. -1. -1. -1.  1.  0.  1.]
 [-1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1.]]
Matriz L 
 [[ 1.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.]
 [-1. -1. -1.  1.  0.  0.  0.]
 [-1. -1. -1. -1.  1.  0.  0.]
 [-1. -1. -1. -1. -1.  1.  0.]
 [-1. -1. -1. -1. -1. -1.  1.]]
Matriz U 
 [[ 1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  2.]
 [ 0.  0.  1.  0.  0.  0.  4.]
 [ 0.  0.  0.  1.  0.  0.  8.]
 [ 0.  0.  0.  0.  1.  0. 16.]
 [ 0.  0.  0.  0.  0.  1. 32.]
 [ 0.  0.  0.  0.  0.  0. 64.]]
Cantidad de operaciones:  245
B=LU?  Si!
Norma infinito de U:  64.0


#### Ejercicio 3

In [67]:
def generarB(n):
    B = np.zeros((n,n))

    for i in range(n):

        for j in range(n):

            if j == i or j == n-1: 
                B[i][j] = 1
            elif i > j:
                B[i][j] = -1
            else:
                B[i][j] = 0

    return B

Redefino main para trabajar con generarB

In [76]:
def main(n):
    B = generarB(n)
    print('Matriz B \n', B)
    
    L,U,cant_oper = elim_gaussiana(B)
    
    print('Matriz L \n', L)
    print('Matriz U \n', U)
    print('Cantidad de operaciones: ', cant_oper)
    print('B=LU? ' , 'Si!' if np.allclose(np.linalg.norm(B - L@U, 1), 0) else 'No!')
    print('Norma infinito de U: ', np.max(np.sum(np.abs(U), axis=1)) )

In [82]:
main(4)

Matriz B 
 [[ 1.  0.  0.  1.]
 [-1.  1.  0.  1.]
 [-1. -1.  1.  1.]
 [-1. -1. -1.  1.]]
Matriz L 
 [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [-1. -1.  1.  0.]
 [-1. -1. -1.  1.]]
Matriz U 
 [[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 4.]
 [0. 0. 0. 8.]]
Cantidad de operaciones:  46
B=LU?  Si!
Norma infinito de U:  8.0


#### Ejercicio 4


In [93]:
def solveB(n):
    B = generarB(n)
    b = np.random.rand(n)

    x = np.linalg.solve(B, b)

    print(x)

In [94]:
for i in range(10):
    solveB(4)

[ 0.1140621   0.03825174 -0.22532008  0.54514214]
[ 0.28513683 -0.07689857  0.0802521   0.43131633]
[-0.07582252 -0.01515036 -0.08916788  0.71172567]
[ 0.07780488  0.14788199 -0.23161101  0.5837655 ]
[-0.28523092 -0.07718378 -0.23128395  0.38137105]
[-0.01176654  0.00805819  0.05014672  0.7129008 ]
[ 0.05314692 -0.36178514  0.11931024  0.46092762]
[-0.11175523 -0.00521158  0.44427727  0.40697175]
[-0.00630747 -0.23202347  0.19722151  0.26056416]
[ 0.20462876 -0.18165531 -0.12645581  0.45369117]
