<a href="https://colab.research.google.com/github/arielbakal/uba_alc/blob/main/laboratorio/TP1/TP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Ejercicio 1

In [50]:
def met_pot(A,k):
  x = np.random.rand(A.shape[1])
  for i in range(k):
    Ax = A@x
    Ax_norma = np.linalg.norm(Ax)
    x = Ax/Ax_norma
    print(x)
  return x

In [60]:
A = np.array([[3,1],[0,2]])
x = met_pot(A, 50)

[0.94050777 0.33977219]
[0.97766764 0.21015705]
[0.99117718 0.1325436 ]
[0.99637791 0.08503562]
[0.99847321 0.0552382 ]
[0.99934492 0.03619024]
[0.9997156 0.0238479]
[0.99987556 0.0157757 ]
[0.99994526 0.01046284]
[0.99997584 0.0069512 ]
[0.99998931 0.00462348]
[0.99999526 0.0030776 ]
[0.9999979  0.00204963]
[0.99999907 0.00136549]
[9.99999586e-01 9.09913411e-04]
[9.99999816e-01 6.06425149e-04]
[9.99999918e-01 4.04201768e-04]
[9.99999964e-01 2.69431556e-04]
[9.99999984e-01 1.79604910e-04]
[9.99999993e-01 1.19729440e-04]
[9.99999997e-01 7.98164415e-05]
[9.99999999e-01 5.32095454e-05]
[9.99999999e-01 3.54724012e-05]
[1.00000000e+00 2.36479878e-05]
[1.0000000e+00 1.5765201e-05]
[1.00000000e+00 1.05100787e-05]
[1.00000000e+00 7.00669461e-06]
[1.00000000e+00 4.67111883e-06]
[1.00000000e+00 3.11407437e-06]
[1.00000000e+00 2.07604743e-06]
[1.00000000e+00 1.38403066e-06]
[1.00000000e+00 9.22686681e-07]
[1.00000000e+00 6.15124265e-07]
[1.00000000e+00 4.10082759e-07]
[1.00000000e+00 2.73388469e-

In [56]:
def rayleigh(A, x):
  a_valor = ( np.transpose(x)@(A@x) / (np.transpose(x)@x) )
  return a_valor
  print("autovalor =", a_valor)

In [57]:
rayleigh(A,x)

3.0

In [58]:
np.linalg.eigvals(A)

array([3., 2.])

### Ejercicio 2

In [114]:
import random
def genMat(n,m):
  A = np.random.rand(n,m)
  print("A =\n",A)
  B = np.zeros([n,m])
  C = np.zeros([n,m])
  for i in range(n):
    for j in range(m):
      if i == j:
        B[i][j] = random.randint(0,10)
        C[i][j] = B[i][j] + 100
      else :
        rnd = random.randint(0,10) 
        B[i][j] = rnd
        B[j][i] = B[i][j]
        C[i][j] = B[i][j]
        C[j][i] = B[i][j]
  print("B =\n",B)
  print("C =\n",C)


In [115]:
genMat(5,5)

A =
 [[0.70823142 0.52343232 0.69346935 0.70918111 0.48534035]
 [0.82935334 0.84853461 0.59371963 0.84599666 0.51499665]
 [0.92296928 0.50239391 0.69996811 0.31619729 0.96340443]
 [0.36643656 0.7744841  0.05373131 0.88910789 0.81738751]
 [0.97396655 0.13137532 0.33327648 0.8408584  0.56561279]]
B =
 [[ 4.  0.  9.  6.  7.]
 [ 0.  5.  5. 10.  5.]
 [ 9.  5.  3.  1.  8.]
 [ 6. 10.  1.  3.  1.]
 [ 7.  5.  8.  1.  3.]]
C =
 [[104.   0.   9.   6.   7.]
 [  0. 105.   5.  10.   5.]
 [  9.   5. 103.   1.   8.]
 [  6.  10.   1. 103.   1.]
 [  7.   5.   8.   1. 103.]]
