<a href="https://colab.research.google.com/github/arielbakal/uba_alc/blob/main/laboratorio/clase%205/labo05_DescLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

### Ejercicio 3

In [4]:
def sol_matrizTS(L,y): # soluciones de Ly=b siendo L traing sup
  b = L@y
  return b

In [5]:
H = np.array([[1,0,0],[2,3,0],[4,2,1]])
y = np.transpose(np.array([[1,2,3]]))
sol_matrizTS(H,y)

array([[ 1],
       [ 8],
       [11]])

In [6]:
np.tril(H,-1) + np.eye(3)
np.triu(H)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 1]])

In [7]:
H[0][0]

1

#### Ejercicio 4


In [214]:
def elim_gaussiana(A):
    cant_op = 0
    m=A.shape[0]
    n=A.shape[1]
    Ac = A.copy()


    if m!=n:
        print('Matriz no cuadrada')
        return

    for i in range(m-1):

      d = (Ac[i][i])

      for j in range(m-1-i):

        s = -(Ac[j+1+i][i]) / d 
        cant_op += 2

        if i == m-2:

          Ac[j+1+i][i] = -s
          cant_op += 1

        else:

          for p in range(m-1-i):

            Ac[j+1+i][p+1+i] += (s * Ac[i][p+1+i])
            cant_op += 2

          Ac[j+1+i][i] = -s
          cant_op += 1
            
    L = np.tril(Ac,-1) + np.eye(A.shape[0]) 
    U = np.triu(Ac)
    
    return L, U, cant_op

def main():
    #n = 7
    #B = np.eye(n) - np.tril(np.ones((n,n)),-1) 
    #B[:n,n-1] = 1
    B = np.array([[2,1,2,3],[4,3,3,4],[-2,2,-4,-12],[4,1,8,-3]])
    print('Matriz B \n', B)
    
    L,U,cant_oper = elim_gaussiana(B)
    
    print('Matriz L \n', L)
    print('Matriz U \n', U)
    print('Cantidad de operaciones: ', cant_oper)
    print('B=LU? ' , 'Si!' if np.allclose(np.linalg.norm(B - L@U, 1), 0) else 'No!')
    print('Norma infinito de U: ', np.max(np.sum(np.abs(U), axis=1)) )

In [215]:
main()

Matriz B 
 [[  2   1   2   3]
 [  4   3   3   4]
 [ -2   2  -4 -12]
 [  4   1   8  -3]]
Matriz L 
 [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [-1.  3.  1.  0.]
 [ 2. -1.  3.  1.]]
Matriz U 
 [[  2   1   2   3]
 [  0   1  -1  -2]
 [  0   0   1  -3]
 [  0   0   0 -11]]
Cantidad de operaciones:  44
B=LU?  No!
Norma infinito de U:  11
