<a href="https://colab.research.google.com/github/arielbakal/uba_alc/blob/main/laboratorio/clase%205/labo05_DescLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

### Ejercicio 3

In [21]:
def sol_matrizTS(L,y): # soluciones de Ly=b siendo L traing sup
  b = L@y
  return b

In [22]:
H = np.array([[1,0,0],[2,3,0],[4,2,1]])
y = np.transpose(np.array([[1,2,3]]))
sol_matrizTS(H,y)

array([[ 1],
       [ 8],
       [11]])

In [23]:
np.tril(H,-1) + np.eye(3)
np.triu(H)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 1]])

In [24]:
H[0][0]

1

#### Ejercicio 4


In [120]:
def elim_gaussiana(A):
    cant_op = 0
    m=A.shape[0]
    n=A.shape[1]
    Ac = A.copy()
    L = np.eye(m)


    if m!=n:
        print('Matriz no cuadrada')
        return
    
    ## desde aqui -- CODIGO A COMPLETAR

    for i in range(m-1):
      L = np.eye(m)
      for j in range(m-1):
        L[j+1][i] = -(Ac[j+1][i]) / (Ac[i][i])
      Ac = L@Ac
      print("\nL_",i+1," =\n",L)
      print("\n",Ac)



                
    ## hasta aqui
            
    #L = np.tril(Ac,-1) + np.eye(A.shape[0]) 
    #U = np.triu(Ac)
    
    #return L, U, cant_op

In [121]:
A= np.array([ [2,1,2,3],[4,3,3,4],[-2,2,-4,-12],[4,1,8,-3] ])
elim_gaussiana(A)


L_ 1  =
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [-2.  0.  0.  1.]]

 [[ 2.  1.  2.  3.]
 [ 0.  1. -1. -2.]
 [ 0.  3. -2. -9.]
 [ 0. -1.  4. -9.]]

L_ 2  =
 [[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0. -3.  1.  0.]
 [ 0.  1.  0.  1.]]

 [[  2.   1.   2.   3.]
 [  0.  -1.   1.   2.]
 [  0.   0.   1.  -3.]
 [  0.   0.   3. -11.]]

L_ 3  =
 [[ 1.  0.  0.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0. -3.  1.]]

 [[ 2.  1.  2.  3.]
 [ 0. -1.  0.  5.]
 [ 0.  0. -1.  3.]
 [ 0.  0.  0. -2.]]
