<a href="https://colab.research.google.com/github/arielbakal/uba_alc/blob/main/laboratorio/clase%205/labo05_DescLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np

### Ejercicio 1

In [77]:
def elim_gaussiana(A):
    cant_op = 0
    m=A.shape[0]
    n=A.shape[1]
    Ac = A.copy()


    if m!=n:
        print('Matriz no cuadrada')
        return

    for i in range(m-1):

      d = (Ac[i][i])

      for j in range(m-1-i):

        s = -(Ac[j+1+i][i]) / d 
        cant_op += 2

        for p in range(m-1-i):

          Ac[j+1+i][p+1+i] += (s * Ac[i][p+1+i])
          cant_op += 2

        Ac[j+1+i][i] = -s
        cant_op += 1
            
    L = np.tril(Ac,-1) + np.eye(A.shape[0]) 
    U = np.triu(Ac)
    
    return L, U, cant_op

def main():
    n = 7
    B = np.eye(n) - np.tril(np.ones((n,n)),-1) 
    B[:n,n-1] = 1
    print('Matriz B \n', B)
    
    L,U,cant_oper = elim_gaussiana(B)
    
    print('Matriz L \n', L)
    print('Matriz U \n', U)
    print('Cantidad de operaciones: ', cant_oper)
    print('B=LU? ' , 'Si!' if np.allclose(np.linalg.norm(B - L@U, 1), 0) else 'No!')
    print('Norma infinito de U: ', np.max(np.sum(np.abs(U), axis=1)) )

In [78]:
main()

Matriz B 
 [[ 1.  0.  0.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  0.  0.  1.]
 [-1. -1.  1.  0.  0.  0.  1.]
 [-1. -1. -1.  1.  0.  0.  1.]
 [-1. -1. -1. -1.  1.  0.  1.]
 [-1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1.]]
Matriz L 
 [[ 1.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.]
 [-1. -1. -1.  1.  0.  0.  0.]
 [-1. -1. -1. -1.  1.  0.  0.]
 [-1. -1. -1. -1. -1.  1.  0.]
 [-1. -1. -1. -1. -1. -1.  1.]]
Matriz U 
 [[ 1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  2.]
 [ 0.  0.  1.  0.  0.  0.  4.]
 [ 0.  0.  0.  1.  0.  0.  8.]
 [ 0.  0.  0.  0.  1.  0. 16.]
 [ 0.  0.  0.  0.  0.  1. 32.]
 [ 0.  0.  0.  0.  0.  0. 64.]]
Cantidad de operaciones:  245
B=LU?  Si!
Norma infinito de U:  64.0
