In [161]:
import numpy as np

In [162]:
A = np.array([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([5, 5, 10])
print(np.linalg.solve(A, b))

[1.875 2.5   3.125]


In [163]:
def jacobi(matriz, igualdad, iteraciones):

    D = np.diag(np.diag(matriz))

    Mj = np.eye(np.shape(matriz)[0],np.shape(matriz)[1])-(np.linalg.inv(D)@matriz)

    x = np.zeros(np.shape(matriz)[0])

    for i in range(iteraciones):
        x_k = (Mj@x) + (np.linalg.inv(D)@igualdad)

        if np.array_equal(x_k, x):
            print("iteraciones:", i)
            return x_k

        x = x_k
    
    print("No alcanzo la solucion exacta")
    return x

In [164]:
jacobi(A, b, 100)

iteraciones: 36


array([1.875, 2.5  , 3.125])

In [165]:
def gauss_seidel(matriz, igualdad, iteraciones):

    L, D = np.tril(A), np.diag(np.diag(matriz))

    Mgs = np.eye(np.shape(matriz)[0],np.shape(matriz)[1])-(np.linalg.inv(D+L)@matriz)

    x = np.zeros(np.shape(matriz)[0])

    for i in range(iteraciones):
        x_k = (Mgs@x) + (np.linalg.inv(D+L)@igualdad)

        if np.array_equal(x_k, x):
            print("iteraciones:", i)
            return x_k

        x = x_k
    
    print("No alcanzo la solucion exacta")
    return x

In [166]:
gauss_seidel(A, b, 100)

iteraciones: 84


array([1.875, 2.5  , 3.125])

In [167]:
A = np.array([[3,1,1], [2,6,1], [1,1,4]])
b = np.array([5, 9, 6])

In [168]:
jacobi(A, b, 100)

iteraciones: 65


array([1., 1., 1.])

In [169]:
gauss_seidel(A, b, 100)

iteraciones: 81


array([1., 1., 1.])